language: java
jdk: openjdk8
notifications:
  slack:
    secure: jyrgQ+p4a1yuIICOSnZ/02kHv7TKcyNYDVxwYoIn+Dm7uLIs2Zi8xHglnHWMtoWWMM0DJZ2m6twW2CwCLO4QnNOqUX00hxTC310Ye0YWrk9Gq2pjK72VqekYwjFxjSxhAsDeO9KxxaebPEATaDOaMsc+LywYiARwPoEi92joGuaAUygDBCPeerZ2iE0p+FkKu3CaxQyDvVeoCOwU4IYYS3goGrJ9PdCfA+4U+a7N0WFGTsfwewASYmzalhNMFgBYYN5RONNgoeV1sWxnMjLvpBuyp6rXWnmdwnit0eVa40CU2aZwOssa+mRCnvEGWnYmDHQ1Ap7UJg1atHke7fVIvqW+vves/GlM+pNyXf1RxoWNJEr56uHN9bVFvz7DhNvw0WJLB1w0wrqNbrBSafIRMldWUWaJhay1IMH6wGZDSYnn0UcACbhDUKmgbFNCqSZjTNdjzlQFFY6ab9kxwbJUJ85/xcqylnIT72zjcHX4NAPn5Kh8gvzvK0vWnmDyx4tzD8IS/rgY+ReJNvEK4bz3qFvc51dyAkKoe4fzMzoCvMYipz/6xCjsmHe774ZpzQYHCE97TuPZ7ZS8dXaaruMSSUoWaBk70FKRrl6/8RW+B9W748X2YaSM2lQGWLKxlDZ2huZDJQ0w0Fga7TfghMX95uZyI3EZKH/7O67ytyuKfKU=
deploy:
  provider: releases
  api_key:
    secure: ZktRw+QSOARWQazBSam2ul5O2EcPq5ipPP7BsljwlKBoPmJNOAomYW41/vaB9GynLN/PAiXsDOYAvLOCnMUZqh7Xme8zP/hjZ1AV3Ze7yvCpsXIlnXX5aelPCw0/v0ngGmlUNgg1lRzuViJ4/zOaAq8Gij5s84aY42o5ml/xysDY0+NUE4lo+nPeM45q5NRTqGxKZ9A/Y+i6HMSCiQ01/MXQZQQFocSUJ3oPnB/3yAU4KM8WXkWYmJXuLs08XDLN2pD4kPMhJbLHJ4rUamh3Vp+24L12DCziIcIo0z2iar6EQBaBjyWfvE1WQiKb1+3B6A067gcfpqNWtkOnWbI8SENUEfAV9w4f/QOgtxPUguyxMxpKbaMo4XE/lCeCHA0XH7anyCsqijT4vRj5mDIHYsK8xmrVXTWikby5KJIr195kli3wEdgfZ+e8qRcTW49FVvuoqdplDNjlqM7Kle/HjthZ5A0gQ8RjV4v27Kr8uO1dDQL0dUNAre2MhFfAbREwkRHK4C+oAgPviIQEmFFRkscbRmJvU7x6Imbuenffc6Zzn5KhELHLb83M2X6JLcztxhP/vtANsWGyagqu+q4ocDTeyE4AKMHTndk07pF7MVbw0scEq8Tnbxz4K6vpfeNjmmEepsnCzN+V/3+wtLFQCvWowLb/FA83urk0a1omKJA=
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-qualys-plugin
